export {default as NavBar} from './NavBar/NavBar';
export {default as Footer} from './Footer/Footer';
export {default as AllRooms} from './ExploreRooms/AllRooms';
export {default as ContactUs} from './ContactUs/ContactUs';
export {default as AboutUs} from './AboutUs/AboutUs';
export {default as GetStarted} from './GetStarted/GetStarted';
export {default as RoomDetails} from './RoomDetails/RoomDetails';
export {default as Login} from './Login/Login';
export {default as SignUp} from './SignUp/SignUp';
export {default as Book} from './BookingForm/Booking'
export {default as Profile} from './Profile/Profile';
export {default as Gallery} from './Gallery/Gallery';
export {default as AdminDashboard} from './Admin/AdminDashboard';