# Generated by Django 4.2.7 on 2025-12-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_teammember_seed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("double", "Double"),
                    ("suite", "Suite"),
                    ("family_suite", "Family Suite"),
                ],
                max_length=20,
            ),
        ),
    ]
