# Generated by Django 6.0 on 2025-12-11 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0006_create_default_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="accessible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="room",
            name="amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="room",
            name="bed_preference",
            field=models.CharField(blank=True, default="Queen Size", max_length=50),
        ),
        migrations.AddField(
            model_name="room",
            name="breakfast_included",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="room",
            name="cancellation_policy",
            field=models.TextField(blank=True, default="Free cancellation available."),
        ),
        migrations.AddField(
            model_name="room",
            name="check_in",
            field=models.CharField(blank=True, default="2:00 PM", max_length=50),
        ),
        migrations.AddField(
            model_name="room",
            name="check_out",
            field=models.CharField(blank=True, default="11:00 AM", max_length=50),
        ),
        migrations.AddField(
            model_name="room",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="room",
            name="floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="parking",
            field=models.CharField(
                blank=True, default="On-site parking", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="pets_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name="room",
            name="reviews_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="room_service",
            field=models.CharField(
                blank=True, default="Available 24/7", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="size",
            field=models.CharField(blank=True, default="28 sqm", max_length=50),
        ),
        migrations.AddField(
            model_name="room",
            name="smoking_policy",
            field=models.CharField(blank=True, default="Non-smoking", max_length=100),
        ),
        migrations.AddField(
            model_name="room",
            name="special_features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="room",
            name="view",
            field=models.CharField(blank=True, default="City View", max_length=100),
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="rooms/gallery/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="hotel.room",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
    ]
